POST http://localhost:5000/chapters 
Content-Type: application/json

{
    "title": "Mantap"
}

###
GET http://localhost:5000/me
Content-Type: application/json
###
GET http://localhost:5000/courses
Content-Type: application/json
###
POST http://localhost:5000/courses/js/subscribe
Content-Type: application/json
###
POST http://localhost:5000/login 
Content-Type: application/json
Accept: application/json

{
    "email": "humanrizki123@gmail.com",
    "password": "password"
}
###
POST http://localhost:5000/register 
Content-Type: application/json
Accept: application/json

{
    "name": "Udin Surudin",
    "email": "humanrizki123@gmail.com",
    "username": "humanrizki9",
    "password": "password"
}
###
DELETE http://localhost:5000/logout 
Content-Type: application/json
Accept: application/json
